jawah/urllib3.future

- changelog/17.bugfix.rst
- src/urllib3/backend/hface.py
…
We need to remove this altogether soon as we do not depend on the stdlib, we can change the method signature now.
> :bug: Fixed the workaround unpack chunk in the send method when the body is a form-data

- CHANGES.rst
- changelog/16.bugfix.rst
- changelog/17.bugfix.rst
- changelog/18.bugfix.rst
- changelog/8.bugfix.rst
- src/urllib3/_version.py
2.0.932 (2023-09-12)
Bugfixes
--------
- Fixed `assert_hostname` behavior when HTTPSConnection targets HTTP/3 over QUIC (`#8 <https://github.com/jawah/urllib3.future/issues/8>`__)
- Fixed protocol violation for HTTP/2 and HTTP/3 where we sent ``Connection: keep-alive`` when it is
forbidden. (`#16 <https://github.com/jawah/urllib3.future/issues/16>`__)
- Fixed ``unpack_chunk`` workaround function in the ``send`` method when body is multipart/form-data (`#17 <https://github.com/jawah/urllib3.future/issues/17>`__)
- Fixed the flow control when sending a body for a HTTP/2 connection.
The body will be split into numerous chunks if the size exceed the specified blocksize when not
using HTTP/1.1 in order to avoid ProtocolError (flow control) (`#18 …
> :bookmark: Release 2.0.932

- CHANGES.rst
- changelog/20.bugfix.rst
- src/urllib3/_version.py
2.0.933 (2023-09-21)
Bugfixes
--------
- Fixed ``HTTPSConnectionPool`` not accepting and forwarding ``ca_cert_data``. (`#20 <https://github.com/jawah/urllib3.future/issues/20>`__)
> :bookmark: Release 2.0.933

- CHANGES.rst
- changelog/22.misc.rst
- changelog/23.feature.rst
- src/urllib3/_version.py
2.0.934 (2023-09-23)
- Added public `ConnectionInfo` class that will be present in each `HttpConnection` instance.
Passing the kwarg ``on_post_connection`` that accept a callable with a single positional argument
in ``PoolManager.urlopen`` method will result in a call each time a connection is picked out
of the pool. The function will be passed a ``ConnectionInfo`` object.
The same argument (``on_post_connection``) can be passed down to the ``HTTPConnectionPool.urlopen`` method. (`#23 <https://github.com/jawah/urllib3.future/issues/23>`__)
- `#22 <https://github.com/jawah/urllib3.future/issues/22>`__
> :bookmark: Release 2.0.934

- CHANGES.rst
- changelog/26.bugfix.rst
- src/urllib3/_version.py
2.0.935 (2023-10-01)
- Fixed a violation in our QUIC transmission due to sending multiple datagrams at once. (`#26 <https://github.com/jawah/urllib3.future/issues/26>`__)
> :bookmark: Release 2.0.935

- CHANGES.rst
- changelog/28.feature.rst
- src/urllib3/_version.py
2.0.936 (2023-10-01)
- Added support for event ``StreamReset`` to raise a ``ProtocolError`` when received from either h2 or h3. (`#28 <https://github.com/jawah/urllib3.future/issues/28>`__)
> :bookmark: Release 2.0.936

- CHANGES.rst
- src/urllib3/backend/_base.py
- src/urllib3/backend/hface.py
- src/urllib3/connection.py
- src/urllib3/util/ssl_.py
- test/test_ssl.py
- test/with_dummyserver/test_connectionpool.py
- test/with_dummyserver/test_socketlevel.py
- test/with_traefik/test_send_data.py
2.1.901 (2023-10-10)
- Set ``DEFAULT`` (as OpenSSL default list) for ciphers in SSLContext if none is provided instead of Python default.
- Fixed an edge case where the chosen state machine would be indicated not to end stream where it should.
- Fixed a rare case where ``ProtocolError`` was raised instead of ``SSLError`` in the underlying QUIC layer state machine.
- Small performance improvement in sending a body by removing an obsolete logic made for a removed constraint.
- Changed default ``User-Agent`` to ``urllib3.future/x.y.z``.
- Removed a compatibility operation that added a ``Content-Length`` header on request with an unknown body length.
This was present due to a bug in Traefik server. An investigation will be conducted and a relevant issue will be
addressed.
> :bookmark: Release 2.1.901

- .github/workflows/ci.yml
- CHANGES.rst
- dummyserver/handlers.py
- src/urllib3/_base_connection.py
- src/urllib3/_version.py
- src/urllib3/backend/hface.py
- src/urllib3/connectionpool.py
- src/urllib3/contrib/hface/protocols/http2/_h2.py
- src/urllib3/contrib/hface/protocols/http3/_qh3.py
- src/urllib3/poolmanager.py
- src/urllib3/util/request.py
- test/with_dummyserver/test_connectionpool.py
- test/with_dummyserver/test_poolmanager.py
2.1.902 (2023-10-21)
- Fixed an issue where streaming response did not yield data until the stream was closed.
- Unified peercert/issuercert dict output in ConnectionInfo output format when HTTP/3.
- Made body stripped from HTTP requests changing the request method to GET after HTTP 303 "See Other" redirect responses.
Headers ``content-encoding, content-language, content-location, content-type, content-length, digest, last-modified`` are
also stripped in the said case.
Port of the security fix GHSA-g4mx-q9vg-27p4
- ``_TYPE_BODY`` now accept `Iterable[str]` in addition to `Iterable[bytes]`.
> :bookmark: Release 2.1.902

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/backend/_base.py
- src/urllib3/backend/hface.py
- src/urllib3/connection.py
- src/urllib3/connectionpool.py
- src/urllib3/contrib/hface/protocols/http2/_h2.py
- src/urllib3/contrib/hface/protocols/http3/_qh3.py
- src/urllib3/poolmanager.py
- test/with_traefik/test_connectionpool_multiplexed.py
2.2.901 (2023-11-04)
- Fixed several issues with multiplexing.
(i) Fixed max concurrent streams in HTTP/2, and HTTP/3.
(ii) Fixed tracking of unconsumed response prior to try to upgrade the connection (to HTTP/3).
(iii) Fixed (always) releasing multiplexed connections into the pool.
(iv) Fixed request having body being interrupted by the ``EarlyResponse`` exception 'signal'.
> :bug: Fixed several issues with multiplexing

- CHANGES.rst
- pyproject.toml
- src/urllib3/_version.py
- src/urllib3/contrib/hface/protocols/http3/_qh3.py
2.2.902 (2023-11-05)
- Fixed QUIC connection not taking ``cert_data`` due to an accidental variable override.
> :bug: Fixed QUIC connection not taking cert_data due to an accidental variable override

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/backend/_base.py
- src/urllib3/backend/hface.py
- src/urllib3/connectionpool.py
- src/urllib3/poolmanager.py
2.2.904 (2023-11-06)
=================
- Fixed concurrent/multiplexed request overflow in a full connection pool.
- Fixed connection close that had in-flight request (in multiplexed mode), the connection appeared as not idle on clean reuse.
> :bookmark: Release 2.2.904

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/connection.py
- src/urllib3/connectionpool.py
- src/urllib3/contrib/hface/protocols/http2/_h2.py
- test/test_connectionpool.py
- test/with_traefik/test_connectionpool_multiplexed.py
2.2.905 (2023-11-08)
- Fixed loss of a QUIC connection due to an inappropriate check in ``conn.is_connected``.
- Separate saturated (multiplexed) connections from the main pool to a distinct one.
> :bookmark: Release 2.2.905

- CHANGES.rst
- mypy-requirements.txt
- pyproject.toml
- src/urllib3/_version.py
- src/urllib3/backend/hface.py
- src/urllib3/connection.py
- src/urllib3/contrib/hface/protocols/http2/_h2.py
- src/urllib3/contrib/hface/protocols/http3/_qh3.py
- src/urllib3/util/url.py
- test/test_util.py
2.2.906 (2023-11-11)
=================
- Bumped minimum requirement for ``qh3`` to version 0.14.0 in order to drop private calls in ``contrib.hface.protocols._qh3``.
- Cache last 1024 ``parse_url`` function calls as it is costly.
- Fixed incomplete flow control window checks while sending data in HTTP/2.
- Fixed unexpected BrokenPipeError exception in a rare edge case.
- Changed behavior for efficiency around ``socket.recv`` to pull ``conn.blocksize`` bytes regardless of ``Response.read(amt=...)``.
> :bookmark: Release 2.2.906

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/contrib/hface/protocols/http3/_qh3.py
2.2.907 (2023-11-11)
- Reverted relying on ``qh3`` to dynamically retrieve the max concurrent streams allowed before connection saturation.
> :bug: Reverted relying on qh3 to dynamically retrieve the max concurrent streams allowed before connection saturation

- .github/CODEOWNERS
- CHANGES.rst
- README.md
- hatch_build.py
- pyproject.toml
- src/urllib3/_version.py
- src/urllib3/contrib/hface/protocols/_factories.py
- src/urllib3/util/ssl_.py
- test/with_dummyserver/test_poolmanager.py
2.3.900 (2023-11-18)
- Disabled unsafe renegotiation option with TLS by default where applicable.
- Added fallback package ``urllib3_future`` in addition to ``urllib3``. This became increasingly needed as a significant number of projects require ``urllib3`` and accidentally override this fork.
> :bookmark: Release 2.3.900

- CHANGES.rst
- docs/advanced-usage.rst
- pyproject.toml
- src/urllib3/_version.py
- src/urllib3/backend/hface.py
- src/urllib3/connection.py
- src/urllib3/connectionpool.py
- src/urllib3/contrib/hface/protocols/_protocols.py
- src/urllib3/contrib/hface/protocols/http1/_h11.py
- src/urllib3/contrib/hface/protocols/http2/_h2.py
- src/urllib3/contrib/hface/protocols/http3/_qh3.py
- src/urllib3/exceptions.py
- src/urllib3/poolmanager.py
- src/urllib3/util/request.py
- test/with_dummyserver/test_socketlevel.py
- test/with_traefik/test_send_data.py
2.3.901 (2023-11-26)
- Small performance improvement while in HTTP/1.1
- Any string passed down to the body will enforce a default ``Content-Type: text/plain; charset=utf-8`` for safety, unless
you specified a ``Content-Type`` header yourself. The ``charset`` parameter will always be set to ``utf-8``.
It is recommended that you pass ``bytes`` instead of a plain string. If a conflicting charset has been set that
does not refer to utf-8, a warning will be raised.
- Added callable argument in ``urlopen``, and ``request`` named ``on_upload_body`` that enables you to track
body upload progress for a single request. It takes 4 positional arguments, namely:
(total_sent: int, total_to_be_sent: int | None, is_completed: bool, any_error: bool)
total_to_be_sent may be set to …
> :bookmark: Release 2.3.901

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/contrib/resolver/doq/_qh3.py
- src/urllib3/contrib/resolver/dou/_socket.py
- src/urllib3/contrib/resolver/in_memory/_dict.py
- src/urllib3/contrib/resolver/null/__init__.py
- src/urllib3/contrib/resolver/system/_socket.py
- test/contrib/test_resolver.py
- Fixed an issue where a stateless resolver (e.g. nullresolver) could not be recycled.
- Fixed an issue where one would attempt to close a resolver multiple times.
> :bug: Fix two minor issues with resolvers

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/backend/hface.py
- src/urllib3/connection.py
w/ Fixed undesired DGRAM/QUIC preemptive upgrade using insecure protocol.
> :bug: Fixed compatibility with older PyPy 3.7 interpreters when HTTP/3 (qh3) can be unavailable.

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/backend/hface.py
- src/urllib3/connection.py
- src/urllib3/util/ssl_.py
- test/with_dummyserver/test_socketlevel.py
- Fixed a rare case of HTTP/3 being disabled when forwarding a custom SSLContext created.
- Re-introduce ``DEFAULT_CIPHERS`` constant in ``urllib3.util.ssl_`` due to the demands. It contains the Mozilla recommended cipher suite that was introduced in version 2.2.900.
- Fixed handling of OpenSSL 3.2.0 new error message for misconfiguring an HTTP proxy as HTTPS. Ported from urllib3/3271.
- Fixed ``request_sent_latency`` that wasn't computed when request was stopped early (prior to sending the complete body).
> :bookmark: Release 2.4.906

- .github/workflows/ci.yml
- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/util/traffic_police.py
- test/test_poolmanager.py
2.5.902 (2024-02-04)
- Fixed missed cleanup of unused PoolKey stored in ``PoliceTraffic`` upon a full ``PoolManager``.
> Bugfix poolmanager map cleanup

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/util/traffic_police.py
2.5.903 (2024-02-20)
- Fixed an edge case where a simultaneous call to ``get_response()`` without a specific promise could lead to a non-thread safe operation.
> :bug: Fix edge case where a simultaneous call to get_response() 

- CHANGES.rst
- src/urllib3/_async/connectionpool.py
- src/urllib3/_async/poolmanager.py
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/contrib/ssa/__init__.py
- src/urllib3/util/_async/traffic_police.py
- test/with_dummyserver/asynchronous/test_connectionpool.py
2.6.901 (2024-02-28)
- Fixed blocking IO just after HTTP/3 is negotiated in an asynchronous context.
- Added explicit warning in case your pool of connections is insufficiently sized for the given charge in an asynchronous context.
- Fixed automatic retrieval of the issuer certificate in an asynchronous context (``ConnectionInfo``).
> :wrench: Few async improvements (HTTP 3 / DGRAM Sock)

- CHANGES.rst
- docs/conf.py
- docs/reference/contrib/index.rst
- docs/reference/contrib/resolver.rst
- docs/reference/contrib/ssa.rst
- docs/reference/urllib3.connectionpool.rst
- docs/reference/urllib3.util.rst
- src/urllib3/_async/connection.py
- src/urllib3/_async/poolmanager.py
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/_base.py
- src/urllib3/backend/hface.py
- src/urllib3/connection.py
- src/urllib3/connectionpool.py
- src/urllib3/contrib/ssa/__init__.py
- src/urllib3/poolmanager.py
- src/urllib3/util/_async/ssl_.py
- src/urllib3/util/ssl_.py
- test/with_dummyserver/asynchronous/test_connectionpool.py
- test/with_traefik/asynchronous/test_proxy.py
- test/with_traefik/test_proxy.py
2.6.902 (2024-03-04)
- Fixed PyPy error when running asynchronous code on Windows after trying to create a datagram socket.
This error is due to an incomplete implementation of the Windows socket API. We silently disabled HTTP/3
if running PyPy+Windows+asyncio until upstream issue resolution.
- Overall performance improvements for both async and sync calls.
- Fixed ProtocolError (No recent network activity after XYZ) error when it should recycle the connection automatically (sync only).
- Added a user-friendly error message when invoking ``get_response`` from either ``PoolManager`` or ``ConnectionPool`` with anything
else than a ``ResponsePromise``.
> :zap: Various performance improvements

- CHANGES.rst
- dev-requirements.txt
- src/urllib3/_async/connection.py
- src/urllib3/_async/connectionpool.py
- src/urllib3/_async/poolmanager.py
- src/urllib3/_async/response.py
- src/urllib3/_collections.py
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/_base.py
- src/urllib3/backend/hface.py
- src/urllib3/connection.py
- src/urllib3/connectionpool.py
- src/urllib3/contrib/hface/protocols/_protocols.py
- src/urllib3/contrib/hface/protocols/http1/_h11.py
- src/urllib3/contrib/hface/protocols/http2/_h2.py
- src/urllib3/exceptions.py
- src/urllib3/poolmanager.py
- src/urllib3/response.py
- src/urllib3/util/_async/traffic_police.py
- src/urllib3/util/request.py
- src/urllib3/util/traffic_police.py
- test/conftest.py
- test/test_collections.py
- test/test_connectionpool.py
- test/with_dummyserver/asynchronous/test_connectionpool.py
- test/with_dummyserver/test_connectionpool.py
- test/with_traefik/asynchronous/test_connectionpool_multiplexed.py
- test/with_traefik/test_connectionpool_multiplexed.py
2.6.904 (2024-03-17)
- Overall performance improvements for both async and sync calls.
- Removed ``TrafficPolice`` internal caching for obj states of contained elements due to its inability to be up-to-date in some cases.
- Fixed SSLError wrong message displayed when using the underlying ``qh3`` library (HTTP/3 only).
- Fixed graceful shutdown for rare HTTP/2 servers configured to immediately forbid opening new streams.
> 🔖 Release 2.6.904

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/util/_async/traffic_police.py
- src/urllib3/util/traffic_police.py
Not really problematic per say, but rather a efficiency matter.
> :bug: Fix traffic police shutdown procedure to avoid killing needlessly a new connection or pool

- CHANGES.rst
- src/urllib3/_async/connection.py
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/_base.py
- src/urllib3/backend/hface.py
- src/urllib3/connection.py
- src/urllib3/util/_async/ssl_.py
- src/urllib3/util/ssl_.py
2.6.906 (2024-03-18)
- Fixed SSL context cache construction that did not take key_password into account.
- Prefer return ``NotImplemented`` instead of raising ``NotImplementedError`` to avoid polluting the stack trace when trying to
initialize the external tls layer when not concerned (e.g. not http3 over QUIC).
> :bug: Fix SSL context cache construction that did not take key_password into account

- CHANGES.rst
- README.md
- docs/advanced-usage.rst
- src/urllib3/_async/connectionpool.py
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/connectionpool.py
- src/urllib3/contrib/resolver/_async/doh/_urllib3.py
- src/urllib3/contrib/resolver/_async/in_memory/_dict.py
- src/urllib3/contrib/resolver/_async/protocols.py
- src/urllib3/contrib/resolver/doh/_urllib3.py
- src/urllib3/contrib/resolver/in_memory/_dict.py
- src/urllib3/contrib/resolver/protocols.py
- src/urllib3/poolmanager.py
- test/__init__.py
- test/contrib/asynchronous/test_resolver.py
- test/contrib/test_resolver.py
- test/with_dummyserver/asynchronous/test_happy_eyeballs.py
- test/with_dummyserver/test_happy_eyeballs.py
2.7.900 (2024-03-25)
- Added Happy-Eyeballs support.
This feature is disabled by default, you can enable it by passing ``happy_eyeballs=True``
into ``AsyncPoolManager``, ``AsyncHTTPConnectionPool`` or its synchronous counterparts.
See the documentation to learn more.
- Fixed an issue where passing a IPv6 address to the in-memory resolver provider would be improperly registered.
- Fixed unclosed socket when the user attempt to set a impossible port to bind on (i.e. not in range 0-65535) leading to a ResourceWarning.
- Fixed a rare issue with DNS-over-HTTPS where a HTTPS record would also be interpreted as a normal record.
> :sparkle: Add support for Happy Eyeballs

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/backend/_async/_base.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/_base.py
- src/urllib3/backend/hface.py
- src/urllib3/exceptions.py
- test/with_dummyserver/test_connectionpool.py
- test/with_dummyserver/test_socketlevel.py
2.7.901 (2024-03-27)
- Fixed an edge case with Response::read() confusing situation where passing a positive amount to read then
passing ``None`` n-times would continuously return cached data if the stream was closed (content consumed).
- Fixed IncompleteRead exception property ``expected`` that did not contain the "remaining" amount expected but rather
the total expected.
> :bug: Fix an edge case with Response::read() passing positive amt then None (repeated n-times) would return cached (buffer) data

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- CHANGES.rst
- pyproject.toml
- src/urllib3/_version.py
- src/urllib3/contrib/hface/protocols/http2/_h2.py
2.7.905 (2024-04-28)
- Added support for ``jh2>=5,<6`` instead of ``h2~=4.0`` as a drop-in replacement.
Expect a significant performance improvement with HTTP/2. We successfully reduced our dependency footprint to the minimum.
> :sparkle: Add support for jh2 instead of h2

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/hface.py
- test/with_traefik/asynchronous/test_connection.py
- test/with_traefik/test_connection.py
Passing a ssl context containing manually loaded root certificates no longer is ignored with HTTP/3 over QUIC.
Close #113
> :bug: Fix usage of custom ssl context in conjunction of HTTP/3

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/hface.py
2.7.910 (2024-05-22)
- Removed workaround for a bug that existed in qh3 < 1.0 with cryptography in a concurrent (thread) environment.
- Avoid loading qh3 at runtime in order to improve import delay. It was used to probe HTTP/3 support. We compute it lazily from now on.
- Added the possibility to use the ``preemptive_quic_cache`` MutableMapping to exclude endpoints.
If your implementation discard the recently set key/entry it will prevent the connection from upgrading itself.
> :zap: improve import performance by lazy loading qh3

- CHANGES.rst
- pyproject.toml
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/hface.py
- src/urllib3/contrib/hface/__init__.py
- src/urllib3/contrib/hface/_configuration.py
- src/urllib3/contrib/hface/_error_codes.py
- src/urllib3/contrib/hface/_typing.py
- src/urllib3/contrib/hface/events/__init__.py
- src/urllib3/contrib/hface/events/_events.py
- src/urllib3/contrib/hface/protocols/__init__.py
- src/urllib3/contrib/hface/protocols/_factories.py
- src/urllib3/contrib/hface/protocols/_protocols.py
- src/urllib3/contrib/hface/protocols/http1/__init__.py
- src/urllib3/contrib/hface/protocols/http1/_h11.py
- src/urllib3/contrib/hface/protocols/http2/__init__.py
- src/urllib3/contrib/hface/protocols/http2/_h2.py
- src/urllib3/contrib/hface/protocols/http3/__init__.py
- src/urllib3/contrib/hface/protocols/http3/_qh3.py
- src/urllib3/util/ssl_.py
- Fixed unset ``tls_version`` within ``ConnectionInfo`` when using the legacy TLSv1 protocol.
- Fixed license metadata SPDX in package.
- Fixed custom ssl context with ``OP_NO_TLSv1_3`` option that did not disable HTTP/3.
- Fixed custom ssl context with ``assert_hostname=False`` parameter not forwarded to QUIC configuration.
> :bookmark: Release 2.7.912

- CHANGES.rst
- pyproject.toml
- src/urllib3/_version.py
- src/urllib3/backend/_async/_base.py
- src/urllib3/backend/_base.py
- src/urllib3/backend/hface.py
- test/contrib/asynchronous/test_resolver.py
- test/contrib/test_resolver.py
2.7.914 (2024-06-15)
- Further improved compatibility with some third party programs that accessed hazardous materials within http.client standard library.
- Add "ARM64" architecture for qh3 automatic installation on Windows.
> :sparkle: Improve http.client deep compatibility offered by us

- CHANGES.rst
- README.md
- docs/advanced-usage.rst
- src/urllib3/_async/connection.py
- src/urllib3/_version.py
- src/urllib3/backend/_async/_base.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/_base.py
- src/urllib3/backend/hface.py
- src/urllib3/connection.py
- test/with_traefik/asynchronous/test_svn.py
- test/with_traefik/test_protolevel.py
- test/with_traefik/test_svn.py
It was already possible to force HTTP/3 using a fake entry in the quic preemptive cache, but now you can leverage the main protocol toggles to do it.
> :sparkle: HTTP/2 with prior knowledge, and HTTP/3 with prior knowledge through svn toggles

- CHANGES.rst
- src/urllib3/_async/response.py
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/hface.py
- src/urllib3/exceptions.py
- src/urllib3/response.py
- test/test_response.py
- test/with_dummyserver/test_socketlevel.py
2.8.901 (2024-06-27)
- Improved compatibility with httplib exception for ``IncompleteRead`` that did not behave exactly like expected (repr/str format over it).
- The metric TLS handshake delay was wrongfully set when using HTTP/2 over cleartext.
- Fixed compatibility with some third-party mocking library that are injecting io.BytesIO in HTTPResponse.
In some cases, ``IncompleteRead`` might not be raised like expected.
> :art: minor adjustments for compatibility purposes

- .github/workflows/ci.yml
- CHANGES.rst
- dev-requirements.txt
- docs/async.rst
- noxfile.py
- pyproject.toml
- src/urllib3/_async/connection.py
- src/urllib3/_async/connectionpool.py
- src/urllib3/_request_methods.py
- src/urllib3/_typing.py
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/hface.py
- src/urllib3/connection.py
- src/urllib3/contrib/emscripten/__init__.py
- src/urllib3/http2.py
- src/urllib3/util/request.py
- test/with_dummyserver/asynchronous/test_connectionpool.py
- Added support for async iterable yielding either bytes or str when passing a body into your requests.
- Added dummy module (e.g. http2 and emscriptem) like upstream without serving any of them. Those modules won't be served and are empty as we diverged since.
- Added a better error message for http3 handshake failure to help out users figuring out what is happening.
- Added official support for Python 3.13
> :bookmark: Release 2.8.902

- CHANGES.rst
- src/urllib3/_version.py
- traefik/macos.sh
- Added ``IS_PYOPENSSL`` constant that is exposed by upstream in ``urllib3.util.ssl_`` submodule.
- Fixed missing exception (``ImportError``) when importing ``urllib3.contrib.pyopenssl`` when PyOpenSSL isn't present in environment.
- Lowered and simplified testing requirements for HTTP/2, and HTTP/3.
- Added ``boto3``, ``sphinx``, and ``requests`` to our downstream test cases (nox).
> :bookmark: Release 2.8.903

- .github/workflows/integration.yml
- CHANGES.rst
- README.md
- ci/0005-DockerPy-FixBadChunk.patch
- noxfile.py
- src/urllib3/_collections.py
- src/urllib3/_version.py
- src/urllib3/contrib/hface/protocols/http1/_h11.py
- Relaxed h11 constraint around "pending proposal" and coming server event about upgrade. This is made to ensure near perfect compatibility against the legacy urllib3 which is based on http.client.
- Fixed h11 yielding bytearray instead of bytes in rare circumstances.
- Added ``docker-py`` in our CI/integration pipeline.
> :bookmark: Release 2.8.904

- CHANGES.rst
- README.md
- dev-requirements.txt
- pyproject.toml
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/hface.py
- src/urllib3/contrib/socks.py
- src/urllib3/poolmanager.py
- src/urllib3/util/retry.py
- src/urllib3/util/ssl_.py
- test/contrib/asynchronous/test_resolver.py
- test/contrib/test_resolver.py
- test/test_retry.py
- test/with_dummyserver/asynchronous/test_poolmanager.py
- test/with_dummyserver/test_https.py
- test/with_dummyserver/test_poolmanager.py
- test/with_traefik/asynchronous/test_send_data.py
- test/with_traefik/test_send_data.py
- Fixed wrong upgrade attempt to QUIC when using a SOCKS proxy. Any usage of a proxy disable HTTP/3 over QUIC as per documented. until proper support is implemented in a next minor version.
- Backported upstream urllib3 #3434: util/ssl: make code resilient to missing hash functions. In certain environments such as in a FIPS enabled system, certain algorithms such as md5 may be unavailable. Due to the importing of such a module on a system where it is unavailable, urllib3(-future) will crash and is unusable. https://github.com/urllib3/urllib3/pull/3434
- Backported upstream urllib3 GHSA-34jh-p97f-mpxf: Strip Proxy-Authorization header on redirects. Added the ``Proxy-Authorization`` header to the list of headers to strip from requests when redirecting to a different host. As before, …
> :bookmark: Release 2.8.905

- src/urllib3/_async/connection.py
- src/urllib3/connection.py
- test/with_dummyserver/test_socketlevel.py
- test/with_traefik/asynchronous/test_send_data.py
- test/with_traefik/test_send_data.py
This PR aims to fix a bug I encountered when using a library that depends on urllib3.future in the same venv as boto3. This is I believe the same issue raised in #133.
Please let me know if there's a more robust change we could make than just converting to string in-place.
> fix: Ensure str header values in connection.py

- .github/workflows/ci.yml
- CHANGES.rst
- docker-compose.win.yaml
- docker-compose.yaml
- src/urllib3/_async/connection.py
- src/urllib3/_async/connectionpool.py
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/_base.py
- src/urllib3/backend/hface.py
- src/urllib3/connection.py
- src/urllib3/connectionpool.py
- src/urllib3/contrib/hface/protocols/_protocols.py
- src/urllib3/contrib/hface/protocols/http2/_h2.py
- traefik/patched.Dockerfile
…
Originally found at https://github.com/internetstandards/Internet.nl/issues/1485
> :bug: fix http2 maximum frame size error when the remote explicitly set a lower value than the default blocksize

- .github/workflows/ci-dead-things.yml
- .github/workflows/ci.yml
- CHANGES.rst
- README.md
- docs/index.rst
- src/urllib3/_async/connection.py
- src/urllib3/_async/connectionpool.py
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/hface.py
- src/urllib3/connection.py
- src/urllib3/connectionpool.py
- src/urllib3/contrib/ssa/__init__.py
- src/urllib3/contrib/webextensions/_async/protocol.py
- src/urllib3/contrib/webextensions/_async/raw.py
- src/urllib3/contrib/webextensions/_async/ws.py
- src/urllib3/contrib/webextensions/protocol.py
- src/urllib3/contrib/webextensions/raw.py
- src/urllib3/contrib/webextensions/ws.py
- src/urllib3/exceptions.py
- src/urllib3/util/retry.py
- test/with_traefik/asynchronous/test_svn.py
- test/with_traefik/asynchronous/test_webextensions.py
- test/with_traefik/test_svn.py
- test/with_traefik/test_webextensions.py
2.10.903 (2024-10-12)
- Fixed exception leaks in ExtensionFromHTTP plugins. Now every extension behave and raise urllib3 own exceptions.
- Added automatic connection downgrade HTTP/2 -> HTTP/1.1 or HTTP/3 -> (HTTP/2 or HTTP/1.1) in case of known recoverable issues. https://github.com/jawah/niquests/issues/150 https://github.com/jawah/niquests/issues/134
- Fixed a rare issue where the write semaphore (async context) for a datagram socket would be locked forever in case of an error.
> Release 2.10.903

- src/urllib3/contrib/emscripten/__init__.py
The extra "install" slipped in from https://github.com/jawah/urllib3.future/commit/46f3bce4ab6ae96bf3c6fbdc05e7a502763f5f16 commit
> Doc: Fix emcscripten warning with too much install arguments

- CHANGES.rst
- README.md
- docs/advanced-usage.rst
- mypy-requirements.txt
- noxfile.py
- src/urllib3/_async/connectionpool.py
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/hface.py
- src/urllib3/connectionpool.py
- src/urllib3/contrib/resolver/_async/factories.py
- src/urllib3/contrib/resolver/factories.py
- test/test_response.py
2.11.903 (2024-10-22)
- Fixed (low-level) exception leak when using ``get_response(...)`` after ``urlopen(..., multiplexed=True)``.
- Fixed erroneous calculated maximal wait when starting a connection upgrade to a higher protocol version in rare cases (async+windows only).
> Fix multiplex err leak

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/hface.py
- src/urllib3/contrib/ssa/__init__.py
2.11.905 (2024-10-26)
- Fixed custom loop like uvloop needing advanced error handling on transport close.
- Fixed MacOS connection reset by peer handling to detect connection close (continuation of fix in 2.11.902)
> Bugfix uvloop and mac rst

- CHANGES.rst
- docs/conf.py
- dummyserver/server.py
- pyproject.toml
- src/urllib3/_async/connection.py
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/hface.py
- src/urllib3/connection.py
- src/urllib3/contrib/resolver/_async/doq/_qh3.py
- src/urllib3/contrib/resolver/_async/dou/_socket.py
- src/urllib3/contrib/resolver/_async/protocols.py
- src/urllib3/contrib/resolver/protocols.py
- src/urllib3/contrib/ssa/__init__.py
- src/urllib3/util/ssl_.py
- test/__init__.py
- test/test_util.py
- test/with_dummyserver/asynchronous/test_connectionpool.py
- test/with_dummyserver/asynchronous/test_poolmanager.py
- test/with_dummyserver/test_connection.py
- test/with_dummyserver/test_connectionpool.py
- test/with_dummyserver/test_https.py
- test/with_traefik/asynchronous/test_conn_info.py
- test/with_traefik/asynchronous/test_connection.py
- test/with_traefik/asynchronous/test_connection_multiplexed.py
- test/with_traefik/asynchronous/test_svn.py
- test/with_traefik/test_conn_info.py
- test/with_traefik/test_connection.py
- test/with_traefik/test_connection_multiplexed.py
- test/with_traefik/test_svn.py
2.11.908 (2024-11-03)
- Fixed async connection shutdown in HTTP/1.1 and HTTP/2 leaving a ``asyncio.TransportSocket`` and ``_SelectorSocketTransport`` partially closed.
- Added automatic mitigation of using deprecated ``PROTOCOL_TLS_*`` constants in ``ssl_version`` parameter.
> :bug: fix async connection shutdown in HTTP/1.1 and HTTP/2 leaving a `asyncio.TransportSocket` and `_SelectorSocketTransport` partially closed

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/contrib/resolver/_async/protocols.py
- src/urllib3/contrib/resolver/protocols.py
- src/urllib3/contrib/ssa/__init__.py
- test/conftest.py
- test/with_traefik/asynchronous/test_connection.py
- test/with_traefik/test_connection.py
2.11.910 (2024-11-08)
- Improved reliability of reusing a specific outgoing port. The feature is no longer experimental.
> :bug: improve outgoing port reuse in same process execution flow (sync&async)

- CHANGES.rst
- README.md
- docs/advanced-usage.rst
- noxfile.py
- src/urllib3/_async/connectionpool.py
- src/urllib3/_async/poolmanager.py
- src/urllib3/_version.py
- src/urllib3/backend/_async/_base.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/_base.py
- src/urllib3/backend/hface.py
- src/urllib3/connectionpool.py
- src/urllib3/contrib/hface/protocols/http1/_h11.py
- src/urllib3/contrib/webextensions/__init__.py
- src/urllib3/contrib/webextensions/_async/__init__.py
- src/urllib3/contrib/webextensions/_async/protocol.py
- src/urllib3/contrib/webextensions/_async/sse.py
- src/urllib3/contrib/webextensions/protocol.py
- src/urllib3/contrib/webextensions/sse.py
- src/urllib3/poolmanager.py
- test/with_traefik/asynchronous/test_connection.py
- test/with_traefik/asynchronous/test_webextensions.py
- test/with_traefik/test_webextensions.py
2.12.900 (2024-11-28)
- Added built-in support for Server-Side-Event (or SSE) via a WebExtension.
It is as simple as doing ``pm.urlopen("GET", "sse://sse.dev/test")``. ``sse`` is using https under the hood by default.
To force SSE via plain HTTP, replace ``sse://`` by ``psse://``.
The ``extension`` attribute of produced response will be set, and you will be able to consume event promptly.
See the documentation to learn more.
- Fixed unintentional regression using ``CONNECT`` verb manually outside of its standard usage.
- Fixed using a WebExtension with ``urlopen(..., multiplexed=True)`` from a PoolManager instance.
> Release 2.12.900

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- CHANGES.rst
- docs/user-guide.rst
- dummyserver/server.py
- pyproject.toml
- src/urllib3/_async/response.py
- src/urllib3/_version.py
- src/urllib3/contrib/webextensions/_async/ws.py
- src/urllib3/contrib/webextensions/ws.py
- src/urllib3/response.py
2.12.909 (2024-01-20)
- Fixed compatibility with upstream urllib3 when third party program invoke deprecated ``HTTPResponse.getheader`` or
``HTTPResponse.getheaders``. Those methods were planned to be removed in 2.1 (they still have a pending deprecation
that mention 2.1 target in the 2.3 version). As such we immediately restore the methods. (#203)
- Implemented our copy of ``HTTPResponse.read1`` heavily simplified as we do already support ``HTTPResponse.read(-1)``.
Also mirrored in ``AsyncHTTPResponse.read1``.
- Automatically grab ``qh3`` for X86 based processors (e.g. win32).
- Fixed the aggressive exception in our native websocket implementation when a server responded positively to an upgrade
request without the required http header. Instead of ``RuntimeError``, …
> Release 2.12.909

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/contrib/hface/protocols/http3/_qh3.py
- src/urllib3/util/url.py
2.12.913 (2024-03-21)
- Added useful repr for ``PoolManager``, ``ConnectionPool`` and ``TrafficPolice`` (async counterpart included).
- Fixed ``KeyError`` upon parsing X509 certificate pulled from the QUIC layer when the certificate contain an unexpected
rfc4514 attribute. (https://github.com/jawah/urllib3.future/issues/217)
> Release 2.12.913

- CHANGES.rst
- src/urllib3/_async/connectionpool.py
- src/urllib3/_async/poolmanager.py
- src/urllib3/_version.py
- src/urllib3/connectionpool.py
- src/urllib3/poolmanager.py
- src/urllib3/util/_async/traffic_police.py
- src/urllib3/util/traffic_police.py
2.12.914 (2024-03-30)
- Fixed a rare thread safety issue when the size of PoolManager is inferior to the thread count. An edge case permitted
the creation of two ``ConnectionPool`` for the same ``PoolKey``.
- Changed the default behavior of threads management to not raise an exception if the thread count is greater than
the pool size. Making it that way better align with upstream, our initial decision revealed itself to cause
confusions for some of our users. No longer will urllib3-future raise ``OverwhelmedTraffic`` in default configuration.
- Fixed an error when ``happy_eyeballs=True`` is set with more tasks or threads than the pool size.
> Release 2.12.914

- CHANGES.rst
- src/urllib3/_async/connection.py
- src/urllib3/_async/connectionpool.py
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/hface.py
- src/urllib3/connection.py
- src/urllib3/connectionpool.py
2.12.917 (2024-04-10)
- Improve keepalive handling for connections. We now listen for an incoming pong frame after emitting a ping frame.
Moreover we ensure better strictness around set ``keepalive_delay`` and consider every connection dropped after set delay. (Close https://github.com/jawah/niquests/issues/240)
> Release 2.12.917

- .github/workflows/ci-dead-things.yml
- .github/workflows/ci.yml
- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/contrib/hface/protocols/http3/_qh3.py
2.12.918 (2024-04-19)
- Fixed http3 QUIC idle timeout did not force the connection to be dropped by the pool.
> Fix http3 idle timeout is terminated

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/hface.py
- src/urllib3/contrib/hface/_stream_matrix.py
- src/urllib3/contrib/hface/protocols/http1/_h11.py
- src/urllib3/contrib/hface/protocols/http2/_h2.py
- src/urllib3/contrib/hface/protocols/http3/_qh3.py
- src/urllib3/contrib/resolver/_async/doh/_urllib3.py
- src/urllib3/contrib/resolver/_async/doq/_qh3.py
- src/urllib3/contrib/resolver/_async/dou/_socket.py
- src/urllib3/contrib/resolver/doh/_urllib3.py
- src/urllib3/contrib/resolver/doq/_qh3.py
- src/urllib3/contrib/resolver/dou/_socket.py
- src/urllib3/contrib/resolver/protocols.py
- src/urllib3/contrib/resolver/utils.py
- src/urllib3/util/_async/traffic_police.py
- test/contrib/test_resolver.py
2.12.920 (2024-05-04)
- Removed the persisting session ticket after first QUIC handshake. In a effort to be stricter with security and align
with our TLS 1.2 and 1.3 ``OP_NO_TICKET`` parameter.
- Improved performance in our event unpacking logic inside state machine protocols. (micro-scale improvements)
- Improved our RDATA (DNS) parsing for HTTPS records toward our ECH (Encrypted Client Hello) support coming soon.
- Fixed a rare HTTP/2 compatibility issue with servers that don't acknowledge our settings (missing ACK frame).
> Release 2.12.920

- .coveragerc
- .github/workflows/ci.yml
- CHANGES.rst
- dev-requirements.txt
- docker-compose.win.yaml
- docker-compose.yaml
- docs/advanced-usage.rst
- noxfile.py
- pyproject.toml
- src/urllib3/_async/connection.py
- src/urllib3/_version.py
- src/urllib3/connection.py
- src/urllib3/contrib/imcc/__init__.py
- src/urllib3/contrib/imcc/_ctypes.py
- src/urllib3/contrib/imcc/_shm.py
- src/urllib3/contrib/ssa/__init__.py
- src/urllib3/response.py
- src/urllib3/util/_async/ssl_.py
- src/urllib3/util/ssl_.py
- test/conftest.py
- test/with_dummyserver/test_https.py
- traefik/patched.Dockerfile
2.12.921 (2024-05-17)
- Extended in-memory mTLS loading support to every major platforms.
- Added support for built-in zstandard starting from Python 3.14 onward.
- Improved test suite execution speed using pytest-xdist.
- Fixed a rare edge case where the CAStore would be empty after upgrade to a HTTP/3 connection when no CA bundle are given before.
This error occurred due to load_default_certs not being applied for the QUIC connection.
> Release 2.12.921

- CHANGES.rst
- pyproject.toml
- src/urllib3/_async/connection.py
- src/urllib3/_async/poolmanager.py
- src/urllib3/_version.py
- src/urllib3/connection.py
- src/urllib3/poolmanager.py
- src/urllib3/util/_async/ssl_.py
- src/urllib3/util/ssl_.py
- test/conftest.py
- test/test_poolmanager.py
- test/test_ssl.py
- test/test_util.py
- test/with_dummyserver/asynchronous/test_poolmanager.py
- test/with_dummyserver/test_https.py
- test/with_dummyserver/test_poolmanager.py
- test/with_dummyserver/test_socketlevel.py
2.13.900 (2024-06-22)
- Fixed passing ``ca_cert_data`` as ``bytes`` instead of ``str``.
- Backported Security fix CVE-2025-50181 (5.3 Medium, GHSA-pq67-6m6q-mj2v) from upstream urllib3 v2.5.0
- Fixed backward incompatible change on the ssl configuration when urllib3-future is invoked by other than Niquests.
The default cipher list will fallback to system's default when Niquests is not the invoker. Also stop setting
``OP_NO_RENEGOTIATION`` in ssl_options when it's not Niquests.
- Fixed a rare bug causing the connection to improperly upgrade to QUIC when no ssl ca are given.
- Updated the low bound version requirement for ``qh3`` to v1.5.3 due to some significant improvement toward
unifying PKI validation behaviors with Python default expectation (w/ OpenSSL).
- …
> Release 2.13.900

- CHANGES.rst
- src/urllib3/_async/connection.py
- src/urllib3/_version.py
- src/urllib3/connection.py
- src/urllib3/util/_async/ssl_.py
- src/urllib3/util/ssl_.py
- src/urllib3/util/ssltransport.py
- test/test_connection.py
- test/test_ssl.py
- test/test_util.py
- test/with_dummyserver/test_socketlevel.py
2.13.904 (2024-08-20)
- Improved performance when creating TLS connection. We removed a redundant ssl_ctx creation due to our
caching / reusability for ssl.SSLContext.
- Fixed forcing disabling SSL renegotiation when explicitly setting ``@SECLEVEL=0`` in the cipher suite.
- Fixed ssl_ctx caching invalidation when ca_certs and/or ca_cert_dir file/directory changed.
> Release 2.13.904

- CHANGES.rst
- ci/0001-Mark-100-Continue-tests-as-failing.patch
- pyproject.toml
- src/urllib3/_async/connection.py
- src/urllib3/_version.py
- src/urllib3/connection.py
- test/with_dummyserver/test_socketlevel.py
- test/with_traefik/asynchronous/test_send_data.py
- test/with_traefik/test_send_data.py
2.13.906 (2024-08-27)
- Fixed charset transparency setter to not enforce ``charset=utf-8`` in Content-Type anymore due to incompatibilities found
in widely requested servers that still don't parse HTTP headers appropriately. We saw a 3rd party report that
a server rejected a request because it expected Content-Type to be exactly "X" and not "X; charset=utf-8".
> Release 2.13.906

- CHANGES.rst
- src/urllib3/_async/connectionpool.py
- src/urllib3/_async/response.py
- src/urllib3/_version.py
- src/urllib3/backend/hface.py
- src/urllib3/contrib/ssa/__init__.py
- src/urllib3/contrib/webextensions/_async/protocol.py
- src/urllib3/contrib/webextensions/protocol.py
- src/urllib3/response.py
- src/urllib3/util/response.py
2.13.907 (2024-09-09)
- Fixed unhandled error in HTTP/3 upgrade (TCP+TLS to QUIC) procedure that mainly affect Windows users.
If your network silently filter QUIC packets or UDP is unreliable outside of your local network the
upgrade procedure could raise an exception instead of silently giving up on QUIC.
- Fixed the accidental leaking of ``MustRedialException`` error in the consumption of the response (including WS or SEE).
> Release 2.13.907

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/backend/_async/hface.py
- src/urllib3/backend/hface.py
2.13.908 (2024-09-10)
- Fixed an edge case where a server would interrupt a SSE without error by closing the connection instead of using the FIN bit
on the last data chunk.
> Release 2.13.908

- CHANGES.rst
- src/urllib3/_version.py
- src/urllib3/util/request.py
- test/with_dummyserver/asynchronous/test_connectionpool.py
2.13.909 (2025-09-14)
- Fixed handling async iterable as body for upload. The logic for chunking the body into socket "blocksize" had a
flaw.
> Release 2.13.909
