.github/workflows/ci.yml, dev-requirements.txt, test/__init__.py, test/conftest.py, test/with_dummyserver/test_https.py, test/with_dummyserver/test_socketlevel.py
=> Enable HTTP/2 and HTTP/3 tests on MacOS

changelog/16.bugfix.rst, src/urllib3/backend/hface.py
=> :bug: Fixed protocol violation when the Connection header is sent for HTTP/2 and HTTP/3

changelog/23.feature.rst, src/urllib3/__init__.py, src/urllib3/_base_connection.py, src/urllib3/backend/__init__.py, src/urllib3/backend/_base.py, src/urllib3/backend/hface.py, src/urllib3/connectionpool.py, src/urllib3/contrib/hface/protocols/_protocols.py, src/urllib3/contrib/hface/protocols/http3/_qh3.py, test/with_dummyserver/test_https.py, test/with_traefik/test_conn_info.py, test/with_traefik/test_proxy.py
A callable hook is added in PoolManager and HttpConnPool (on_post_connection), allowing you to retrieve it (ConnectionInfo) in flight.
=> :sparkle: Added ConnectionInfo class that will be present in each HttpConnection instance.

CHANGES.rst, src/urllib3/_version.py, src/urllib3/backend/_base.py, src/urllib3/backend/hface.py, src/urllib3/contrib/hface/protocols/http2/_h2.py, src/urllib3/contrib/hface/protocols/http3/_qh3.py
2.2.903 (2023-11-06)
- Improved overall performances in HTTP/2, and HTTP/3, with or without multiplexed.
=> :zap: Improved overall performances in HTTP/2, and HTTP/3, with or without multiplexed

CHANGES.rst, src/urllib3/_version.py, src/urllib3/connection.py
=> :bug: Fix compatibility with the boto3 library when sending data

CHANGES.rst, README.md, src/urllib3/_version.py, src/urllib3/backend/_async/hface.py, src/urllib3/backend/hface.py, src/urllib3/contrib/hface/protocols/http2/_h2.py, src/urllib3/poolmanager.py
2.6.903 (2024-03-10)
- Overall performance improvements for both async and sync calls.
=> :zap: Various performance improvements

CHANGES.rst, docs/user-guide.rst, mypy-requirements.txt, pyproject.toml, src/urllib3/_version.py, src/urllib3/backend/_async/hface.py, src/urllib3/backend/hface.py, src/urllib3/contrib/hface/protocols/http3/_qh3.py
qh3 just got his first major version. no more external dependencies, faster, and safer.
this PR address its support by fixing introduced breaking changes.
=> :sparkle: Add support for qh3 >1.0,<2

CHANGES.rst, src/urllib3/_version.py, src/urllib3/connectionpool.py, src/urllib3/util/_async/traffic_police.py, src/urllib3/util/traffic_police.py
…
traffic_state_of is a critical function that is called many times. any improvement there result in noticeable performance bump.
=> :zap: improve traffic_state_of function by simplifying the if-else condition cost

CHANGES.rst, src/urllib3/_constant.py, src/urllib3/_version.py, src/urllib3/contrib/hface/protocols/http1/_h11.py, test/with_traefik/asynchronous/test_send_data.py, test/with_traefik/test_send_data.py
and also reduce amt of call to _maybe_next_cycle in http/1.1 state machine handler
=> :zap: improve download performance for a large quantity of data

CHANGES.rst, src/urllib3/_version.py, src/urllib3/backend/_async/hface.py, src/urllib3/backend/hface.py, test/with_traefik/asynchronous/test_protolevel.py, test/with_traefik/test_protolevel.py
Related to https://github.com/jawah/niquests/issues/125
=> :bug: Fix accept custom Host header for HTTP/2 and HTTP/3

CHANGES.rst, src/urllib3/_async/connectionpool.py, src/urllib3/_version.py, src/urllib3/backend/_async/hface.py, src/urllib3/backend/hface.py, src/urllib3/connectionpool.py
=> :bug: Fix incompatible method signature HTTPConnectionPool._new_conn

CHANGES.rst, src/urllib3/_async/connection.py, src/urllib3/_async/response.py, src/urllib3/_version.py, src/urllib3/connection.py, src/urllib3/response.py, test/test_informational.py
=> :bug: fix (early) informational response attempt to read their bodies

CHANGES.rst, src/urllib3/_async/connectionpool.py, src/urllib3/_version.py, src/urllib3/backend/_async/hface.py, src/urllib3/backend/hface.py, src/urllib3/connectionpool.py, test/with_dummyserver/test_socketlevel.py
fix https://github.com/jawah/niquests/issues/161
=> :sparkle: add viable replacement for connection close detection

.coveragerc, CHANGES.rst, dev-requirements.txt, docker-compose.win.yaml, docker-compose.yaml, noxfile.py, src/urllib3/_async/connectionpool.py, src/urllib3/_version.py, src/urllib3/backend/_async/hface.py, src/urllib3/backend/hface.py, src/urllib3/connectionpool.py
2.11.907 (2024-10-30)
- Fixed attempt to send ping frame in our discrete background idle watcher when the connection has just been closed.
=> Release 2.11.907

CHANGES.rst, src/urllib3/_async/connectionpool.py, src/urllib3/_version.py, src/urllib3/connectionpool.py, src/urllib3/contrib/_socks_override.py, src/urllib3/contrib/resolver/_async/doq/_qh3.py, src/urllib3/contrib/resolver/_async/dot/_ssl.py, src/urllib3/contrib/resolver/_async/dou/_socket.py, src/urllib3/contrib/resolver/_async/protocols.py, src/urllib3/contrib/resolver/doq/_qh3.py, src/urllib3/contrib/resolver/dot/_ssl.py, src/urllib3/contrib/resolver/dou/_socket.py, src/urllib3/contrib/resolver/utils.py, src/urllib3/contrib/ssa/__init__.py, src/urllib3/contrib/ssa/_timeout.py, src/urllib3/exceptions.py, test/contrib/asynchronous/test_resolver.py, test/contrib/test_resolver.py
possible answer to edge case seen at https://github.com/jawah/niquests/issues/183
=> :zap: improve timeout reliability in async mode

CHANGES.rst, docs/advanced-usage.rst, src/urllib3/_async/connectionpool.py, src/urllib3/_async/poolmanager.py, src/urllib3/connectionpool.py, src/urllib3/poolmanager.py, src/urllib3/util/_async/traffic_police.py, src/urllib3/util/traffic_police.py, test/test_poolmanager.py
=> :sparkle: add useful repr for pools

CHANGES.rst, docker-compose.win.yaml, docker-compose.yaml, src/urllib3/_async/response.py, src/urllib3/_version.py, src/urllib3/backend/_async/_base.py, src/urllib3/backend/_base.py, src/urllib3/response.py, src/urllib3/util/response.py
2.12.915 (2024-04-02)
- Fixed a performance issue when streaming download by chunk (size) not in phase with incoming packets size.
See https://github.com/jawah/niquests/issues/236
=> Fix streaming download performance issue

CHANGES.rst, docker-compose.win.yaml, docker-compose.yaml, src/urllib3/_async/connectionpool.py, src/urllib3/_async/poolmanager.py, src/urllib3/_async/response.py, src/urllib3/_version.py, src/urllib3/connectionpool.py, src/urllib3/contrib/hface/_stream_matrix.py, src/urllib3/contrib/hface/protocols/http1/_h11.py, src/urllib3/contrib/hface/protocols/http2/_h2.py, src/urllib3/contrib/hface/protocols/http3/_qh3.py, src/urllib3/poolmanager.py, src/urllib3/response.py, src/urllib3/util/_async/traffic_police.py, src/urllib3/util/traffic_police.py
2.12.919 (2024-04-28)
- Fixed http3 has_expired logic to take into account "client side abort without close event". https://github.com/jawah/niquests/issues/240
- Improved performances in our state machine protocols.
- Fixed PoolManager allocation when maxsize is reached (async). https://github.com/jawah/niquests/issues/247
- Fixed PoolManager response mapping per pool memory leak.
=> Release 2.12.919

CHANGES.rst, src/urllib3/_async/connection.py, src/urllib3/_version.py, src/urllib3/connection.py
2.12.922 (2024-05-19)
- Fixed a minor performance regression when reopening or upgrading a HTTPS connection.
=> Fix perf ssl ctx

CHANGES.rst, docker-compose.win.yaml, docker-compose.yaml, src/urllib3/_version.py, src/urllib3/backend/_async/_base.py, src/urllib3/backend/_base.py
2.13.901 (2024-08-02)
- Fixed a memory leakage when downloading large content and specifying a chunk size
that is lower than your regular incoming chunk size. (https://github.com/jawah/niquests/issues/270)
=> Release 2.13.901
